#cloud-config
## Set hostname
hostname: ${hostname}

## Modifying root password
chpasswd:
  list: |
    root:root
  expire: False

## Enable direct root access
disable_root: false

## Allow ssh password authentication
ssh_pwauth: true

## Setup users and ssh keys
users:
  - name: vfricou
    gecos: Vincent Fricou
    groups: root
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBDm5ZCYzVCTP4+MBE9+921LXbj5rKLsWVUzqQjPoAp1 vfricou - Vincent FRICOU <vincent(at)fricouv(dot)eu>
  - name: root
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBDm5ZCYzVCTP4+MBE9+921LXbj5rKLsWVUzqQjPoAp1 vfricou - Vincent FRICOU <vincent(at)fricouv(dot)eu>

## Update resolv.conf file
write_files:
  - path: /etc/resolv.conf
    content: nameserver ${net_nameserver}

## Install packages
packages:
  - qemu-guest-agent
  - python
